### PR TITLE
Add Slint (Rust) implementation

### PR DESCRIPTION
**Pull request by ogoffart**

### CODE REVIEW

**Comment by ogoffart** [comment]
@dumblob  ping

**Comment by dumblob** [comment]
Hi @ogoffart , thanks for providing this example! Could you please also add the author designation (might be also a name of a group if there is no single author) and the link to the author's/group's profile?

Thanks and sorry for the delay.

**Comment by ogoffart** [comment]
Done

**Comment by dumblob** [comment]
Thanks a lot @ogoffart and enjoy Slint!

**Pull request merged**
